name: al_ashraf
description: A mobile application for android and ios using flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.5
  firebase_auth: ^3.3.5
  flutter_local_notifications: ^9.2.0
  lottie: ^1.1.0
  shared_preferences: ^2.0.6
  get: ^4.6.1
  auto_size_text: ^3.0.0
  webview_flutter: ^3.0.0
  flutter_inappwebview: ^5.3.2
  web_scraper: ^0.1.4
  connectivity_plus: ^2.0.3
  http: ^0.13.3
  url_launcher: ^6.0.17
  just_audio: ^0.9.18
  rxdart: ^0.27.3
  syncfusion_flutter_pdfviewer: ^19.4.43-beta
  epubx: ^3.0.0
  provider: ^6.0.2
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  marquee: ^2.2.0
  in_app_review: ^2.0.4
  share_plus: ^3.0.4
  just_audio_background: ^0.0.1-beta.4
  in_app_update: ^2.0.0
  new_version: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.3




  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash_image/alkobba_splash.png"
  android: true
  ios: true
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/main_screen_image/main_screen_image.jpg
    - assets/images/who_are_we_screen_image/who_are_we_screen_image.JPG
    - assets/images/contact_us_screen_image/contact_us_screen_image.JPG
    - assets/images/who_are_we_screen_image/twitter64.png
    - assets/images/who_are_we_screen_image/world-wide-web64.png
    - assets/images/who_are_we_screen_image/youtube64.png
    - assets/images/contact_us_screen_image/facebook64.png
    - assets/images/contact_us_screen_image/outlook64.png
    - assets/images/contact_us_screen_image/whatsapp64.png
    - assets/images/radio_screen_image/radio_screen_image.png
    - assets/images/back_ground_image/back_ground.jpg
    - assets/images/contact_us_screen_image/gmail64.png
    - assets/lottie_gifs/home_screen/posts.json
    - assets/lottie_gifs/home_screen/favourite_posts.json
    - assets/lottie_gifs/home_screen/diwans.json
    - assets/lottie_gifs/home_screen/nathr_books.json
    - assets/lottie_gifs/home_screen/radio.json
    - assets/lottie_gifs/home_screen/hadra_book.json
    - assets/lottie_gifs/home_screen/ahadeth.json
    - assets/lottie_gifs/home_screen/inshad.json
    - assets/lottie_gifs/home_screen/who_are_we.json
    - assets/lottie_gifs/home_screen/contact_us.json
    - assets/lottie_gifs/home_screen/rate_app.json
    - assets/lottie_gifs/home_screen/share.json
    - assets/books/pdf/hadra/الحضرة كاملة الطبعة 29 بدون هوامش.pdf
    - assets/images/books_screen/background_search.png
    - assets/images/books_screen/hadra_cover.jpg
    - assets/books/pdf/diwan/ديوان الأسير1.pdf
    - assets/books/pdf/diwan/ديوان العتيق2.pdf
    - assets/books/pdf/diwan/ديوان الطليق3.pdf
    - assets/books/pdf/diwan/ديوان الغريق4.pdf
    - assets/books/pdf/diwan/ديوان الرفيق5.pdf
    - assets/books/pdf/diwan/ديوان الحقيق6.pdf
    - assets/books/pdf/diwan/ديوان العقيق7.pdf
    - assets/books/pdf/diwan/ديوان الوثيق8.pdf
    - assets/books/pdf/diwan/ديوان الرحيق9.pdf
    - assets/books/pdf/diwan/ديوان البريق10.pdf
    - assets/books/pdf/diwan/ديوان الفية محمد صلى الله عليه وسلم11.pdf
    - assets/books/pdf/diwan/ديوان محمد الإمام المبين12.pdf
    - assets/books/pdf/diwan/ديوان العشيق13.pdf
    - assets/books/pdf/diwan/ديوان الرشيق14.pdf
    - assets/books/pdf/diwan/ديوان الرقيق15.pdf
    - assets/books/pdf/diwan/ديوان المفيق16.pdf
    - assets/books/pdf/diwan/ديوان العريق17.pdf
    - assets/books/pdf/diwan/ديوان الفريق18.pdf
    - assets/books/pdf/diwan/ديوان الشفيق19.pdf
    - assets/books/pdf/diwan/ديوان الوفيق20.pdf
    - assets/books/pdf/diwan/ديوان فى حب أشرف البرية.pdf
    - assets/images/books_screen/diwan_cover/alaseer.jpg
    - assets/images/books_screen/diwan_cover/alateek.jpg
    - assets/images/books_screen/diwan_cover/altaleek.jpg
    - assets/images/books_screen/diwan_cover/alghareek.jpg
    - assets/images/books_screen/diwan_cover/alrafeek.jpg
    - assets/images/books_screen/diwan_cover/alhakeek.jpg
    - assets/images/books_screen/diwan_cover/alakeek.jpg
    - assets/images/books_screen/diwan_cover/alwatheek.jpg
    - assets/images/books_screen/diwan_cover/alraheek.jpg
    - assets/images/books_screen/diwan_cover/albareek.jpg
    - assets/images/books_screen/diwan_cover/alfeyya.jpg
    - assets/images/books_screen/diwan_cover/alemam.jpg
    - assets/images/books_screen/diwan_cover/alasheek.jpg
    - assets/images/books_screen/diwan_cover/dewan-alrasheq.jpg
    - assets/images/books_screen/diwan_cover/alrarkek.jpg
    - assets/images/books_screen/diwan_cover/elmafeeq.jpg
    - assets/images/books_screen/diwan_cover/alaareq.jpg
    - assets/images/books_screen/diwan_cover/alfareek.jpg
    - assets/images/books_screen/diwan_cover/alshafeeq.jpg
    - assets/images/books_screen/diwan_cover/alwafeek.jpg
    - assets/images/books_screen/diwan_cover/ashrf-albarya.jpg
    - assets/books/epub/diwan_epub_with_tashkil.epub
    - assets/books/epub/diwan_epub_without_tashkil.epub
    - assets/books/pdf/nathr/ihsanAll.pdf
    - assets/books/pdf/nathr/imanAll.pdf
    - assets/books/pdf/nathr/islamAll.pdf
    - assets/books/pdf/nathr/mishkaa.pdf
    - assets/books/pdf/nathr/nabiAll.pdf
    - assets/books/pdf/nathr/osool.pdf
    - assets/images/books_screen/nathr_books_covers/islam.jpg
    - assets/images/books_screen/nathr_books_covers/iman.jpg
    - assets/images/books_screen/nathr_books_covers/osool.jpg
    - assets/images/books_screen/nathr_books_covers/ihsan.jpg
    - assets/images/books_screen/nathr_books_covers/mishkaa.jpg
    - assets/images/books_screen/nathr_books_covers/nabeena.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
